site_name: Anime Bump
site_description: Design documentation for Anime Bump
site_author: sasthim
site_url: https://sasthim.github.io/anime-bump/

plugins:
  - search
  - awesome-pages

theme:
  name: material

  palette:
    - scheme: slate
      primary: deep purple
      accent: cyan

  features:
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy